name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/namespace3/actions

    - name: Build docker images using cache
      uses: whoan/docker-build-with-cache-action@v2
      with:
        # Docker's registry user
        username: "${{ secrets.DOCKER_USERNAME }}"
        # Docker's registry password
        password: "${{ secrets.DOCKER_PASSWORD }}"
        # (Optional) Docker registry (default: Docker Hub's registry)
        registry: registry.cn-hangzhou.aliyuncs.com
        # Name of the image to build
        image_name: namespace3/actions
        # (Optional) Tag of the image to build (default: latest)
        push_image_and_stages: false
