name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish Docker Action
      uses: lj
      with:
        # Username used to login docker registry
        username: jing.ljljlj
        # Password used to login docker registry
        password: Hello0616
        # Docker registry server address
        registry: registry.cn-hangzhou.aliyuncs.com
        # Docker file used to build image
        repository: namespace3/actions
