name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build docker images using cache
      uses: whoan/docker-build-with-cache-action@v2
      with:
        # Docker's registry user
        username: jing.ljljlj
        # Docker's registry password
        password: Hello0616
        # (Optional) Docker registry (default: Docker Hub's registry)
        registry: registry.cn-hangzhou.aliyuncs.com
        # Name of the image to build
        image_name: namespace3/actions
        # (Optional) Tag of the image to build (default: latest)
